### ISSUE TITLE
A few issues. Including I believe one of the spotify category playlists id doesnt work.

### ISSUE THREAD

**Issue by nath2125** [rocstack/plex-playlist-sync#1]
Throw category doesn't work, from what I can see, looking into your repository. 

After taking out the throw category, still getting errors in logs also.

My docker compose:
```
version: "2.1"
services:
  playlistSync:
    image: silkychap/plex-playlist-sync:latest
    container_name: playlist-sync
    # optional only if you chose WRITE_MISSING_AS_CSV=1 in env
    volumes:
      - /mnt/user/Media/plexplaylistsync:/data
    environment:
      - PLEX_URL=xxx
      - PLEX_TOKEN=xxx # Owners/Primary user's plex token
      - PLEX_TOKEN_USERS=xxx # Other managed user's plex tokens
      - PLEX_MIN_SONGS=1 # Minimum number of songs for a playlist to be created
      - WRITE_MISSING_AS_CSV=1 # Default 0, 1 = writes missing tracks from each playlist to a csv
      - APPEND_SERVICE_SUFFIX=1 # Default 1, 1 = appends the service name to the playlist name
      - ADD_PLAYLIST_POSTER=1 # Default 1, 1 = add poster for each playlist
      - ADD_PLAYLIST_DESCRIPTION=1 # Default 1, 1 = add description for each playlist
      - APPEND_INSTEAD_OF_SYNC=0 # Default 0, 1 = Sync tracks, 0 = Append only
      - SECONDS_TO_WAIT=84000
      - SPOTIFY_CLIENT_ID=xxx
      - SPOTIFY_CLIENT_SECRET=xxx
      - SPOTIFY_PLAYLIST_IDS=279oyMcEoa9deD0YTGzaXh, 2XyKmMJCz8kBerzW13xEO0, 2tOEtJ3aNi4u77nDRX2K1o, 4X6I2YyjuQM40vk5G2M3oi # List of playlist ids
      - SPOTIFY_CATEGORIES=throw, featured, top, hiphop, mood, party, dance, rnb, rock # List of categories to add playlists from
    restart: unless-stopped
```

Log Screenshot after composing the container:
![image](https://github.com/rocstack/plex-playlist-sync/assets/99367069/04d81f57-cab2-4abe-acf6-bbccb84bce75)
